name: gh-pages
on: 
  issue_comment:
    types: [created, deleted]
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        shell: bash
        run: |
          pip install --upgrade pip
          pip install tox
          tox -av
